### PR TITLE
Typesafe -> Lightbend

### PR DESCRIPTION
**Pull request by SethTisue**
the key commit here is 570cfe0, the rest is just housekeeping.
hopefully 570cfe0 will fix the regression in CLA checking

### CODE REVIEW

**Comment by dwijnand** [comment]
For Lightbend! Against darkness and rigidity!

(ok it's out of my system now, moving on)

**Comment by SethTisue** [comment]
:flags: :fist:

**Comment by SethTisue** [comment]
might as well merge #58 at the same time

**Comment by adriaanm** [comment]
:rainbow:

**Comment by SethTisue** [comment]
seems to be working

**Comment by adriaanm** [comment]
It looks like the restart script isn't working. All I did was `ssh scabot killall java`

**Pull request merged**
