### PR TITLE
Remove Scabot's web UI

### PR DESCRIPTION
**Pull request by dwijnand**
As mentioned in https://github.com/scala/scabot/pull/93#issuecomment-452363176

### CODE REVIEW

**Comment by SethTisue** [comment]
there should be code that could be deleted, too?

**Comment by dwijnand** [comment]
Oh yeah :)

**Comment by dwijnand** [comment]
Better?

**Comment by adriaanm** [comment]
Let's not touch scabot. It's going to be a bit more work to tease apart the UI and the webhooks. There are two routes (github and jenkins) that are core functionality, not UI.

**Comment by adriaanm** [comment]
(Sorry, again, more friendly: let's defer until after 2.13.0 is out.)

**Comment by dwijnand** [comment]
Ah, I see.  I'll open issues instead.

**Comment by dwijnand** [comment]
#95 and #96

**Comment by adriaanm** [comment]
thanks :)

**Pull request closed without merging**
