### PR TITLE
Remove the web UI without losing the non-UI routes

### LINKED ISSUE #95: Remove the web UI without losing the non-UI routes
Scabot contains a web UI that isn't used and can go.

An initial attempt at this was made in #94 without realising there are important non-UI routes that can't be lost.

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #95

### CODE REVIEW

**Comment by dwijnand** [comment]
What a prankster... 😛

**Comment by SethTisue** [comment]
@dwijnand ?

**Comment by dwijnand** [comment]
I had assumed when you said you were interested you meant you were ready to merge this PR.  Then when you didn't merge it I thought maybe it wasn't a priority any more.

It's not a priority for me to get this merged, and I use my personal PR queue (https://github.com/pulls) as a tracker of in progress work, so I (re)closed this as a result.

**Comment by SethTisue** [comment]
if you reopen it, I will merge it.

sometimes my cycle time — the time it takes me to get back to something — is longer than 3 days

**Comment by SethTisue** [comment]
thanks!

**Pull request merged**
