### PR TITLE
remove obsolete "review by" feature

### PR DESCRIPTION
**Pull request by SethTisue**
the GitHub web UI supports this directly now

### CODE REVIEW

**Comment by SethTisue** [comment]
this will give Scabot more time for leisure activities with her family.

**Comment by hrhino** [comment]
Don't you need write access to request a reviewer through the UI?

**Comment by SethTisue** [comment]
> Don't you need write access to request a reviewer through the UI?

well...... I think the awareness of the existence of this feature in scabot among people who don't already have the necessary access to use the official GitHub feature is just about zero. it's just another thing for people to learn (and forget) — I really don't think we've have added this feature to begin with if the GitHub feature had existed back then. I think it's better to just go with the GitHub flow unless something is really a pronounced value-add.

**Comment by SethTisue** [comment]
okay nbd

**Pull request closed without merging**
